mutation CreateDesigners($input: [DesignerCreateInput!]!) {
  createDesigners(input: $input) {
    designers {
      id
      name
      email
      password
      createTime
    }
  }
}

{
  "input": [
    {
      "name": "Tom",
      "email": "tom@gmail.com",
      "password": "tomtom"
    }
  ]
}


mutation PublishProduct($create: DesignerRelationInput, $where: DesignerWhere) {
  updateDesigners(create: $create, where: $where) {
    designers {
      id
      name
      email
      products {
        id
        name
        price
      }
    }
  }
}

{
  "create": {
    "products": [
      {
        "node": {
          "name": "gold ring",
          "price": 19.99
        }
      }
    ]
  },
  "where": {
    "id": "ca7d5fd8-4ee4-4715-9cb6-7076187956c5"
  }
}


mutation CreateCategories($input: [CategoryCreateInput!]!) {
  createCategories(input: $input) {
    categories {
      id
      name
      products {
        id
        name
        price
      }
    }
  }
}


{
  "input": [
    {
      "name": "Rings",
      "products": {
        "connect": [
          {
            "where": {
              "node": {
                "id": "842ec176-88d3-4f6c-ae71-71885501ebb0"
              }
            }
          }
        ]
      }
    }
  ]
}


mutation CreateUsers($input: [UserCreateInput!]!) {
  createUsers(input: $input) {
    users {
      id
      username
      email
      password
      createTime
    }
  }
}


{
  "input": [
    {
      "username": "Mary",
      "email": "mary@gmail.com",
      "password": "marymary"
    }
  ]
}

mutation AddToCart($connect: UserConnectInput, $where: UserWhere) {
  updateUsers(connect: $connect, where: $where) {
    users {
      id
      username
      email
      cart {
        id
        name
        price
        designers {
          id
          name
        }
      }
    }
  }
}

{
  "connect": {
    "cart": [
      {
        "where": {
          "node": {
            "id": "3ce93fe2-5cbb-480b-a925-fe4df1108214"
          }
        },
        "edge": {
          "amount": 1
        }
      }
    ]
  },
  "where": {
    "id": "eb83c001-bddc-45e3-bed3-357e52c5c706"
  }
}


mutation CartToLike($where: UserWhere, $connect: UserConnectInput, $disconnect: UserDisconnectInput) {
  updateUsers(where: $where, connect: $connect, disconnect: $disconnect) {
    users {
      id
      username
      liked {
        id
        name
        price
      }
      cart {
        id
        name
        price
      }
    }
  }
}


{
  "where": {
    "id": "eb83c001-bddc-45e3-bed3-357e52c5c706"
  },
  "connect": {
    "liked": [
      {
        "where": {
          "node": {
            "id": "842ec176-88d3-4f6c-ae71-71885501ebb0"
          }
        }
      }
    ]
  },
  "disconnect": {
    "cart": [
      {
        "where": {
          "node": {
            "id": "842ec176-88d3-4f6c-ae71-71885501ebb0"
          }
        }
      }
    ]
  }
}

mutation PlaceOrder($where: UserWhere, $create: UserRelationInput) {
  updateUsers(where: $where, create: $create) {
    users {
      id
      username
      email
      cart {
        id
        name
        price
      }
      orders {
        id
        createTime
        products {
          id
          name
          price
        }
      }
    }
  }
}

{
  "where": {
    "id": "eb83c001-bddc-45e3-bed3-357e52c5c706"
  },
  "create": {
    "orders": [
      {
        "node": {
          "products": {
            "connect": [
              {
                "connect": [
                  {
                    "userCarted": [
                      {
                        "where": {
                          "node": {
                            "id": "eb83c001-bddc-45e3-bed3-357e52c5c706"
                          }
                        }
                      }
                    ]
                  }
                ],
                "edge": {
                  "amount": 1
                }
              }
            ]
          }
        }
      }
    ]
  }
}